### ISSUE TITLE
failed when upgrade to typescript 1.6.2

### ISSUE THREAD

**Issue by KhoaSydney** [jbrantly/ts-loader#44]
Hi @jbrantly 

I just upgraded Typescript to 1.6.2 and it gives me the following error 
```javascript
ts-loader: Using typescript@1.6.2 and C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\tsconfig.json
C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:1573
                throw new Error("Debug Failure. False expression: " + (message
                ^
Error: Debug Failure. False expression: How could we be trying to update a document that the registry doesn't have?
    at Object.assert (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:1573:23)
    at acquireOrUpdateDocument (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:43097:26)
    at Object.updateDocument (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:43091:20)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:43709:49)
    at tryReuseStructureFromOldProgram (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:35508:42)
    at Object.createProgram (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:35444:14)
    at synchronizeHostData (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:43651:33)
    at Object.getSyntacticDiagnostics (C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\typescript\lib\typescript.js:43755:13)
    at C:\Projects\Midwinter.ReasonableBasis\Midwinter.AdviceOS.Web\node_modules\ts-loader\index.js:304:42
    at Array.forEach (native)
Process terminated with code 1.
```

Do you have any idea on how to fix this error?

cheers,
Khoa

**Comment by KhoaSydney** [comment]
I managed fix the issue above by installing typescript 1.6 for Visual studio. I also replaced old import syntax to the new es6 way. Now I have a different error complaining that `You may need an appropriate loader to handle this file type.`

I came back to to your blog about Typescript with ES6 and able to fix it by using Babel loader as Webpack does not support ES6 yet. 

http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/

**Comment by jbrantly** [comment]
Glad you got it fixed. I've never seen that error before.

ES6 isn't strictly necessary but is certainly the way forward.
